fixtures:
  forge_modules:
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.0.1"
      puppet_version: ">= 6.0.0"
  repositories:
    app_modeling: "https://github.com/puppetlabs/puppetlabs-app_modeling.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    nginx: "https://github.com/voxpupuli/puppet-nginx.git"
    php:
      repo: "https://github.com/voxpupuli/puppet-php.git"
      ref:  "3.4.2"
    haproxy: "https://github.com/puppetlabs/puppetlabs-haproxy.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    wordpress: "https://github.com/hunner/puppet-wordpress.git"
    selinux: "https://github.com/voxpupuli/puppet-selinux.git"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    staging: "https://github.com/voxpupuli/puppet-staging"
    docker: "https://github.com/garethr/garethr-docker.git"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
  symlinks:
    rgbank: "#{source_dir}"
